sonar.verbos=true

sonar.projectKey=my-project-key 

sonar.organization=my-org-key 

sonar.projectName=My Project 

sonar.sources=.

sonar.language=java 

sonar.sourceEncoding=UTF-8 

sonar.java.binaries=target/classes sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
