sonar.verbos=true

sonar.projectKey=lic-key_lic-nspt 

sonar.organization=lic-key

sonar.projectName=lic-nspt 

sonar.sources=.

sonar.language=java 

sonar.sourceEncoding=UTF-8 

sonar.java.binaries=target/classes sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
